In [1]:
!pip install plotly scikit-learn

Requirement already satisfied: plotly in /usr/local/lib/python3.12/dist-packages (5.24.1)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.12/dist-packages (1.6.1)
Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.12/dist-packages (from plotly) (9.1.4)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from plotly) (26.0)
Requirement already satisfied: numpy>=1.19.5 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (2.0.2)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (1.16.3)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (3.6.0)

In [4]:
import pandas as pd
import numpy as np
import plotly.graph_objects as go
from sklearn.linear_model import LinearRegression

In [5]:
hours = pd.date_range(start="2026-03-01", periods=168, freq="H")  # 1 week hourly

usage = []

for h in hours:
    if 18 <= h.hour <= 22:
        usage.append(np.random.randint(250,350))  # evening peak
    else:
        usage.append(np.random.randint(100,180))

df = pd.DataFrame({
    "timestamp": hours,
    "electricity_kwh": usage
})

df.head()

/tmp/ipykernel_1425/747148225.py:1: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  hours = pd.date_range(start="2026-03-01", periods=168, freq="H")  # 1 week hourly

            timestamp  electricity_kwh
0 2026-03-01 00:00:00              129
1 2026-03-01 01:00:00              175
2 2026-03-01 02:00:00              151
3 2026-03-01 03:00:00              121
4 2026-03-01 04:00:00              158

In [6]:
df['moving_avg'] = df['electricity_kwh'].rolling(window=3).mean()

df.head()

            timestamp  electricity_kwh  moving_avg
0 2026-03-01 00:00:00              129         NaN
1 2026-03-01 01:00:00              175         NaN
2 2026-03-01 02:00:00              151  151.666667
3 2026-03-01 03:00:00              121  149.000000
4 2026-03-01 04:00:00              158  143.333333

In [7]:
df['hour_index'] = np.arange(len(df))

X = df[['hour_index']]
y = df['electricity_kwh']

model = LinearRegression()
model.fit(X,y)

df['predicted'] = model.predict(X)

df.head()

            timestamp  electricity_kwh  moving_avg  hour_index   predicted
0 2026-03-01 00:00:00              129         NaN           0  164.096365
1 2026-03-01 01:00:00              175         NaN           1  164.225237
2 2026-03-01 02:00:00              151  151.666667           2  164.354108
3 2026-03-01 03:00:00              121  149.000000           3  164.482980
4 2026-03-01 04:00:00              158  143.333333           4  164.611852

In [8]:
fig = go.Figure()

fig.add_trace(go.Scatter(
    x=df['timestamp'],
    y=df['electricity_kwh'],
    mode='lines',
    name='Actual Usage'
))

fig.add_trace(go.Scatter(
    x=df['timestamp'],
    y=df['moving_avg'],
    mode='lines',
    name='Moving Average'
))

fig.add_trace(go.Scatter(
    x=df['timestamp'],
    y=df['predicted'],
    mode='lines',
    name='Predicted Usage'
))

fig.show()